## 协程

协程，又称微线程，纤程。英文名Coroutine。协程的特点在于是一个线程执行。

> ​	最大的优势就是协程极高的执行效率。因为子程序切换不是线程切换，而是由程序自身控制，因此，没有线程切换的开销，和多线程比，线程数量越多，协程的性能优势就越明显。
>
> ​	只有一个线程，也不存在同时写变量冲突，在协程中控制共享资源不加锁.

通过generator（生成器）实现协程

> ​	在generator中，我们不但可以通过`for`循环来迭代，还可以不断调用`next()`函数获取由`yield`语句返回的下一个值。
>
> `yield`不但可以返回一个值，它还可以接收调用者发出`send()`的参数。

## 方法介绍

- yield  的两种方式 `yield +值`  和 表达式：`变量 = yield + 值`
- next() 适用于直接`yield +值`
- send() 不仅可以启动生成器，还可以发送值到 yield

### next方法

```python
def genFunc():
    yield 1
    yield 2
    yield 3
    return '200 k'


if __name__ == '__main__':
    gen = genFunc()
    # next(gen)
    print(next(gen))# 1
    print(next(gen))# 2
    print(next(gen))# 3
    print(next(gen))# 报错
```

结果：

> 1
> 2
> 3
> Traceback (most recent call last):
>  print(next(gen))
> StopIteration: 200 k

### send方法

```python
def genFunc():
    html = yield 'http://www.baidu.com' #假设这里是一个网络IO，可以生成值和接收值
    print('html:',html) #打印调用者的值：'简化：已经下载好的页面'
    yield 2 # send传值代替了2
    yield 3
    return '200 k'


if __name__ == '__main__':
    gen = genFunc()
    url = next(gen) #获取到generator第一个yield的值
    print('url:',url)# 打印生成器的值 'http://www.baidu.com'
    # 假设这里有一段下载页面的代码
    html='简化：已经下载好的页面'
    gen.send(html)# 传值到生成器，并且启动generator到下一个·yield
    print(next(gen))
```

结果：

>url: http://www.baidu.com
>html: 简化：已经下载好的页面
>3

注意：

- 用send发送一个非None值之前（比如这里的：`gen.send(html)`）应先启动generator，启动方式有两种：

> 1. next 即这里的：`url = next(gen)` 
> 2. `send(None)`

- 一次调用generator，只有一次生产值和接收值。若只有一个yield语句，进行第二次发送值到generator，就会产生异常

### close()方法

顾名思义，关闭generator，但是需要注意：

- 关闭generator之后，就不能再调用此generator，否则`close()`方法会抛`StopIteration`异常 
```python
def genFunc():
    yield 'http://www.baidu.com' #这里close,会有GeneratorExit
    yield 2 
    yield 3
    return '200 k'

if __name__ == '__main__':
    gen = genFunc()
    print(111,next(gen))
    gen.close() 
    next(gen)#这里会抛异常(StopIteration) 因为还有yield 未使用
```
> 在`gen.close()` 执行后会在`yield 'http://www.baidu.com'`抛出`GeneratorExit`异常，所以在下次`next(gen)`就会产生生成器已停止的异常`StopIteration`

- 若是捕获了GeneratorExit的异常后，还有yield未使用，close()方法会抛运行时异常

```python
def genFunc():
    try:
        yield 'http://www.baidu.com' 
    except GeneratorExit:#虽然捕获了生成器异常
        pass
    yield 2 
    yield 3
    return '200 k'

if __name__ == '__main__':
    gen = genFunc()
    print(111,next(gen))
    gen.close() #这里会抛运行时异常 因为还有yield 未使用
```
报错：
> RuntimeError: generator ignored GeneratorExit

### throw方法

- 会在当前的yield下抛出一个异常

```python
def genFunc():
    yield 'http://www.baidu.com' #在这里抛出了异常
    yield 2 
    yield 3
    return '200 k'

if __name__ == '__main__':
    gen = genFunc()
    print(111,next(gen))
    gen.throw(Exception,"异常的描述，比如下载出错")
```
结果：

> 111 http://www.baidu.com
> Traceback (most recent call last):
>  line 10, in <module>
>     gen.throw(Exception,"异常的描述，比如下载出错")
> line 2, in genFunc
>     yield 'http://www.baidu.com' 
> Exception: 异常的描述，比如下载出错

- 这个时候用try捕获后，程序不会报错，就是一般的异常处理了

```python
def genFunc():
    try:
        yield 'http://www.baidu.com'
    except Exception as e:
        print(e)
    yield 2 
    yield 3
    return '200 k'

if __name__ == '__main__':
    gen = genFunc()
    print(111,next(gen))
    gen.throw(Exception,"异常的描述，比如下载出错")
```
结果：

> 111 http://www.baidu.com
> 异常的描述，比如下载出错